### ISSUE TITLE
[Feat] 자세 측정 기능 구현

### ISSUE THREAD

**Issue by HyunJaeyeon** [DeveloperAcademy-POSTECH/2024-MC3-M1-Creamy#21]
## 💡 Feature Issue

-  에어팟을 이용하여 자세를 측정하고 사용자의 바른 자세 기준을 구합니다.

## 🌿  To-do

- [x] 접근 권한 허용
- [x] 5초 동안 사용자의 자세를 받고 기준 자세를 구함
- [x] SwiftData의 goodPosture에 저장
- [x] 측정 실패 시 MeasureErrorView로 이동
