### ISSUE TITLE
[Feat]Onboarding -> MainView 연결 및 PIP화면, SettingView 생성

### ISSUE THREAD

**Issue by HappyDoran** [DeveloperAcademy-POSTECH/2024-MC3-M1-Creamy#28]
## 💡 Feature Issue
MainView에서 HeadphoneMotionManager사용하여 animation 구성
Onboarding에서 MenuExtrabar로 넘어가는 부분 고찰
-> Jen이 HeadphoneMotionManager를 작업하고 있는 중이기 때문에 충돌을 피하기 위해서 건드리지 않는 선에서 생각해볼 것

## 🌿  To-do

- [x] MainView에 HeadphoneMotionManager 연결
- [x] MainView에서 쓰이지만 pip Window에서도 쓰이는 컴포넌트 분리 
- [x] 새로운 창으로 분리하는 방법 알아보기
- [x] SettingView 생성
