### ISSUE TITLE
[Feat] 남은 기능 구현하기

### ISSUE THREAD

**Issue by HyunJaeyeon** [DeveloperAcademy-POSTECH/2024-MC3-M1-Creamy#33]
## 🌿  To-do

- [ ] UI 전부 반영
- [ ] backbutton 커스텀
- [x] HeadphoneMotionManager에 goodPosture, goodPostureRange 가져오기 (swiftData)
- [x] 측정 끝났을 때 backbutton 비활성화
- [x] swiftData의 임의값들 제대로 설정!
