### ISSUE TITLE
[Feat]Linking Swift Data to MainView

### ISSUE THREAD

**Issue by HappyDoran** [DeveloperAcademy-POSTECH/2024-MC3-M1-Creamy#40]
## 💡 Feature Issue
mainView에 SwiftData 연결

## 🌿  To-do

- [ ] TurtleView에 SwiftData 연결
- [ ] Statistic/DayPostureView에 SwiftData 연결
- [ ] DayPosture 로직
- [ ] Statistic/WeekPostureView에 SwiftData 연결
- [ ] RealTimePostureView Airpods 착용 여부에 따른 View 변경
- [ ] 앱 빌드시에 Onboarding을 모두 다 마친 상태라면(User Model의 isFirst값이 false라면) EmptyView에 Popover만 띄우는 작업
