### ISSUE TITLE
[Feat] UT 이후 추가 기능 구현

### ISSUE THREAD

**Issue by HappyDoran** [DeveloperAcademy-POSTECH/2024-MC3-M1-Creamy#62]
## 💡 Feature Issue
UT이후에 추가적으로 해야하는 디벨롭 및 수정

## 🌿  To-do

- [x] Info,plist \n없애기
- [ ] DayPostureView 구현
- [x] RealTimePostureView Text 구현
- [x] 에어팟 시간 체크를 위한 Timer 로직 수정
