### ISSUE TITLE
[Feat] Character Notification location modify

### ISSUE THREAD

**Issue by Junu-Park** [DeveloperAcademy-POSTECH/2024-MC3-M1-Creamy#66]
## 💡 Feature Issue

캐릭터 알림 위치 수정

## 🌿  To-do

- [x] 캐릭터 알림 이미지 변경
- [x] 등장 방향 변경
- [x] 캐릭터 이미지 각도 조절
