### ISSUE TITLE
[Feat] Update MainView

### ISSUE THREAD

**Issue by HappyDoran** [DeveloperAcademy-POSTECH/2024-MC3-M1-Creamy#71]
## 💡 Feature Issue
MainView UI를 업데이트하고, 각각의 상태에 따른 MainView를 구현할 예정입니다.

## 🌿  To-do

- [x] Create UserModel Mode
- [x] Update MainView, RealTimeView
- [x] Create timer Logic
