### ISSUE TITLE
[Feat]Create StatisticView

### ISSUE THREAD

**Issue by HappyDoran** [DeveloperAcademy-POSTECH/2024-MC3-M1-Creamy#74]
## 💡 Feature Issue
자세 알림 모드일때의 DayPostureView 구현
기본 알림 모드일때의 DayPostureView 구현

## 🌿  To-do

- [x] Update DayPostureView (user.notificationMode == .posture)
- [x] Update DayPostureView (user.notificationMode == .default)
- [x] NotiStatistic에 오늘의 최고기록에 해당하는 변수 bestRecord 선언
- [x] currentState에 따른 timer 로직 구현
