### ISSUE TITLE
[Feat] UserModel Modify

### ISSUE THREAD

**Issue by Junu-Park** [DeveloperAcademy-POSTECH/2024-MC3-M1-Creamy#80]
## 💡 Feature Issue

UserModel 수정

## 🌿  To-do

- [ ] 소리ON/OFF 프로퍼티 추가
- [ ] 알림ON/OFF 프로퍼티 추가
- [ ] 시간 알림 주기 프로퍼티 추가
- [ ] worse 자세 알림 주기 프로퍼티 추가
- [ ] bad 자세 알림 주기 프로퍼티 추가
- [ ] noticycle 프로퍼티 삭제
