### ISSUE TITLE
[Feat] Refactor MainView

### ISSUE THREAD

**Issue by HappyDoran** [DeveloperAcademy-POSTECH/2024-MC3-M1-Creamy#82]
## 💡 Feature Issue
MainView Mute 구현 

## 🌿  To-do

- [x] MainView에서 mute가 될때 userDefault에서 sound와 noti 프로퍼티 toggle로 변환되게 구현
- [x] MainView에서 mute 버튼 변경
- [x] MainView에서 나쁜 자세를 취했을 때 보여지는 Text구현
- [x] MainView에서 최고기록을 갱신했을 때 나오는 Text 구현
