### ISSUE TITLE
[Feat] OnboardingView 최종 수정 반영

### ISSUE THREAD

**Issue by HyunJaeyeon** [DeveloperAcademy-POSTECH/2024-MC3-M1-Creamy#83]
## 💡 Feature Issue

- 최종 온보딩 뷰를 반영합니다
## 🌿  To-do

- [ ] 타이틀바-백버튼 컬러 변경
- [x]  기본 알림 뷰 수정 `OnboardingView` 
- [x]  온보딩 자세 측정 뷰 추가 `OnboardingView`
