### ISSUE TITLE
[Feat] 설정뷰 설정 값 연동 구현

### ISSUE THREAD

**Issue by Junu-Park** [DeveloperAcademy-POSTECH/2024-MC3-M1-Creamy#92]
## 💡 Feature Issue

- 설정뷰에서 설정 했을 경우에 값이 연동 되도록 구현해야합니다.
## 🌿  To-do

- [ ] 기본 알림 주기 시간 설정
- [ ] 자세 측정 알림 주기 시간 설정
- [ ] 알림 소리 On/Off 설정
- [ ] 첫 시작에서 자세 측정 알림 선택 후, 시작 시 멈춰버리는 오류 수정
